PRESET_PROMPT='preset-prompt'
CALL_LOGS="call-logs"
OVERVIEW_TABLE="overview"
CPF_CONTRIBUTION_EMPLOYEE="cpf-employee"
CPF_CONTRIBUTION_SELFEMPLOYED="cpf-contribution-selfemployed"
IMPORTANT_INFO="important-info"


INDEXES = [OVERVIEW_TABLE, CPF_CONTRIBUTION_EMPLOYEE, CPF_CONTRIBUTION_SELFEMPLOYED, IMPORTANT_INFO]

INDEXES_TO_CREATE = [PRESET_PROMPT, CALL_LOGS, OVERVIEW_TABLE, CPF_CONTRIBUTION_EMPLOYEE, CPF_CONTRIBUTION_SELFEMPLOYED, IMPORTANT_INFO]