CALL_LOGS="call-logs"
OVERVIEW_TABLE="overview"
CPF_CONTRIBUTION_EMPLOYEE="cpf-employee"
CPF_CONTRIBUTION_SELFEMPLOYED="cpf-contribution-selfemployed"


INDEXES = [OVERVIEW_TABLE, CPF_CONTRIBUTION_EMPLOYEE, CPF_CONTRIBUTION_SELFEMPLOYED]

INDEXES_TO_CREATE = [CALL_LOGS, OVERVIEW_TABLE, CPF_CONTRIBUTION_EMPLOYEE, CPF_CONTRIBUTION_SELFEMPLOYED]