PRESET_PROMPT='preset-prompt'
CALL_LOGS="call-logs"
OVERVIEW_TABLE="overview"
CPF_CONTRIBUTION_EMPLOYEE="cpf-employee"
CPF_CONTRIBUTION_SELFEMPLOYED="cpf-contribution-selfemployed"
IMPORTANT_INFO="important-info"
GOVERNMENT_SUPPORT="government-support"
HOME_OWNERSHIP="home-ownership"
INVESTMENT_AND_INTEREST="investment-and-interest"
MONTHLY_PAYOUT="monthly-payout"
MORE_WAYS_TO_SAVE="more-ways-to-save"
RETIREMENT_WITHDRAWAL="retirement-withdrawal"
SILVER_SUPPORT_SCHEME="silver-support-scheme"


INDEXES = [OVERVIEW_TABLE, CPF_CONTRIBUTION_EMPLOYEE, CPF_CONTRIBUTION_SELFEMPLOYED, IMPORTANT_INFO, HOME_OWNERSHIP, INVESTMENT_AND_INTEREST, MONTHLY_PAYOUT, MORE_WAYS_TO_SAVE, RETIREMENT_WITHDRAWAL, SILVER_SUPPORT_SCHEME]

INDEXES_TO_CREATE = [PRESET_PROMPT, CALL_LOGS, OVERVIEW_TABLE, CPF_CONTRIBUTION_EMPLOYEE, CPF_CONTRIBUTION_SELFEMPLOYED, IMPORTANT_INFO]