import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/features/navbar";
import { LogContextProvider } from "@/lib/context/LogContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LunaAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LogContextProvider>
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
      </LogContextProvider>
    </html>
  );
}
